# Generated by Django 5.2.5 on 2026-01-20 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_branch_appointment_dentist_dentist_contact_number_and_more'),
        ('billing', '0001_initial'),
        ('patient', '0018_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='appointment.appointment'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pending', 'Pending')], default='unpaid', max_length=20),
        ),
    ]
