# Generated by Django 5.2.5 on 2025-09-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('consumable', 'Consumable'), ('equipment', 'Equipment'), ('medicine', 'Medicine'), ('other', 'Other')], max_length=100),
        ),
    ]
