# Generated by Django 5.2.5 on 2025-09-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('consumable', 'Consumable'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=100),
        ),
    ]
