# Generated by Django 5.2.5 on 2026-01-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
