# Generated by Django 5.2.5 on 2025-09-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('servicetype', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('id_no', models.CharField(max_length=255)),
            ],
        ),
    ]
