# Generated by Django 5.2.5 on 2025-09-14 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='dentist',
            new_name='dentist_name',
        ),
    ]
