# Generated by Django 5.2.5 on 2025-09-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_dentist_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.TimeField(),
        ),
    ]
