# Generated by Django 5.2.5 on 2025-09-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='servicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(help_text='Duration of the service (e.g., 00:30:00 for 30 mins)'),
        ),
    ]
