# Generated by Django 5.2.5 on 2025-09-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
