# Generated by Django 5.2.5 on 2025-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_preferred_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('not_arrived', 'Not Yet Arrived'), ('arrived', 'Arrived'), ('ongoing', 'On Going'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='not_arrived', max_length=20),
        ),
    ]
