# Generated by Django 5.2.5 on 2025-11-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='servicetype',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='appointment.service'),
        ),
    ]
