# Generated by Django 5.2.5 on 2025-12-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_remove_appointment_servicetype_appointment_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id_no',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
