# Generated by Django 5.2.5 on 2026-01-06 04:09

from django.conf import settings
from django.db import migrations


def noop(apps, schema_editor):
    # user_id column already exists in the database, so nothing to do here.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_remove_appointment_id_no_alter_appointment_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(noop, reverse_code=migrations.RunPython.noop),
    ]
