# Generated by Django 5.2.5 on 2026-01-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_branch_appointment_dentist_dentist_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General / Consultation'), ('ENDO', 'Endodontics'), ('EXTRACTION', 'Tooth Extraction'), ('IMPLANT', 'Implants'), ('WHITENING', 'Whitening / Bleaching'), ('RESTORATION', 'Restoration'), ('SURGERY', 'Surgery'), ('REMOVABLE_ARCH', 'Removable Prosthodontics (per arch)'), ('COMPLETE_DENTURE', 'Complete Denture'), ('THERMOSENS', 'Thermosens'), ('IVOCAP', 'Ivocap'), ('REMOVABLE_WHITE', 'Removable Prostho (White Plastic)'), ('RPD_METAL', 'RPD Metal Framework'), ('ORTHO', 'Orthodontics'), ('FIXED', 'Fixed Prosthodontics'), ('DENTURE_REPAIR', 'Denture Repair')], default='GENERAL', max_length=50),
        ),
    ]
