# Generated by Django 5.2.5 on 2025-09-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
