# Generated by Django 5.2.5 on 2025-09-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_complaint_remove_patient_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(max_length=11),
        ),
    ]
