# Generated by Django 5.2.5 on 2025-09-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_complaint_remove_patient_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='guest_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
