# Generated by Django 5.2.5 on 2025-09-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_telephone'),
        ('patient', '0003_patient_guest_id_patient_is_guest'),
    ]

    operations = [
    ]
