# Generated by Django 5.2.5 on 2025-09-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_medicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialHistory',
            fields=[
                ('date', models.DateField()),
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('time', models.TimeField()),
                ('type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_history', to='patient.patient')),
            ],
        ),
    ]
