# Generated by Django 5.2.5 on 2025-09-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_financialhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='dentist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='prescriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='service',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='treatment',
            field=models.TextField(blank=True),
        ),
    ]
