# Generated by Django 5.2.5 on 2025-09-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_medicalhistory_date_medicalhistory_dentist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialhistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
