# Generated by Django 5.2.5 on 2025-09-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_financialhistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialhistory',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
