# Generated by Django 5.2.5 on 2025-09-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_financialhistory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialhistory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='financialhistory',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
