# Generated by Django 5.2.5 on 2025-10-04 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tooth_number', models.PositiveIntegerField()),
                ('condition', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograms', to='patient.patient')),
            ],
            options={
                'unique_together': {('patient', 'tooth_number')},
            },
        ),
    ]
