# Generated by Django 5.2.5 on 2025-10-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_odontogram'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='odontogram',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='odontogram',
            name='dentist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='odontogram',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odontogram',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='odontogram',
            name='treatment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
