# Generated by Django 5.2.5 on 2025-12-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_odontogram_unique_together_odontogram_dentist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odontogram',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='odontogram',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='odontogram',
            name='treatment',
        ),
    ]
