# Generated by Django 5.2.5 on 2025-12-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_remove_appointment_servicetype_appointment_services'),
        ('patient', '0014_remove_odontogram_condition_remove_odontogram_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontogram',
            name='service',
            field=models.ManyToManyField(blank=True, to='appointment.service'),
        ),
    ]
