# Generated by Django 5.2.5 on 2026-01-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_odontogram_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='abnormal_bleeding_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='particular_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnancy_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
