# Generated by Django 5.2.5 on 2026-01-28 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_xray'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialhistory',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Billing History', 'verbose_name_plural': 'Billing Histories'},
        ),
        migrations.RemoveField(
            model_name='financialhistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='financialhistory',
            name='number',
        ),
        migrations.RemoveField(
            model_name='financialhistory',
            name='time',
        ),
        migrations.RemoveField(
            model_name='financialhistory',
            name='type',
        ),
        migrations.AddField(
            model_name='financialhistory',
            name='bill_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='financialhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 10, 7, 31, 652053, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='financialhistory',
            name='payment_mode',
            field=models.CharField(default='Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='financialhistory',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialhistory',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialhistory',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
    ]
