# Generated by Django 5.2.5 on 2026-01-28 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_alter_financialhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Treatment History', 'verbose_name_plural': 'Treatment Histories'},
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='service',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='treatment',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='findings',
            field=models.TextField(default='No findings recorded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='procedure',
            field=models.CharField(default='General Consultation', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='dentist',
            field=models.CharField(max_length=200),
        ),
    ]
