# Generated by Django 5.2.5 on 2026-01-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_alter_medicalhistory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='procedure',
            new_name='service',
        ),
    ]
