# Generated by Django 5.2.5 on 2026-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_rename_procedure_medicalhistory_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='service',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='services',
            field=models.TextField(blank=True, default=''),
        ),
    ]
